"""CuratorBrainBase — extracted from the former services/curator_brain.py (Wave 4 split)."""
from ._models import *  # noqa: F401,F403


class CuratorBrainBase:
    def __init__(self):
        brain_dir = Path(settings.data_dir) / "curator_brain"
        brain_dir.mkdir(parents=True, exist_ok=True)

        self._db_path = brain_dir / "brain.db"
        self._conn = self._open_db()
        self._init_tables()

        # Separate LanceDB for embedding-searchable summaries/reflections.
        # NOT the main LanceDB, NOT the knowledge graph LanceDB.
        self._lancedb_path = brain_dir / "lancedb"
        self._lancedb_path.mkdir(parents=True, exist_ok=True)
        try:
            self.vectors = lancedb.connect(str(self._lancedb_path))
        except Exception as e:
            logger.warning(f"[CuratorBrain] LanceDB init failed (non-fatal): {e}")
            self.vectors = None

    def _open_db(self) -> sqlite3.Connection:
        conn = sqlite3.connect(str(self._db_path), check_same_thread=False)
        conn.row_factory = sqlite3.Row      # rows behave like dicts
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA synchronous=NORMAL")
        conn.execute("PRAGMA foreign_keys=ON")
        return conn

    def _init_tables(self):
        self._conn.executescript("""
            CREATE TABLE IF NOT EXISTS notebook_digests (
                notebook_id  TEXT PRIMARY KEY,
                name         TEXT NOT NULL,
                subject      TEXT DEFAULT '',
                current_summary      TEXT,
                key_themes           TEXT DEFAULT '[]',
                key_entities         TEXT DEFAULT '[]',
                cross_notebook_concepts TEXT DEFAULT '[]',
                source_count         INTEGER DEFAULT 0,
                last_source_added    TEXT,
                last_updated         TEXT,
                previous_summary     TEXT,
                dirty                INTEGER DEFAULT 1
            );

            CREATE TABLE IF NOT EXISTS connections (
                id               INTEGER PRIMARY KEY AUTOINCREMENT,
                notebook_a       TEXT NOT NULL,
                notebook_b       TEXT NOT NULL,
                connection_type  TEXT NOT NULL DEFAULT 'shared_concepts',
                description      TEXT NOT NULL,
                evidence         TEXT DEFAULT '[]',
                strength         REAL DEFAULT 0.5,
                discovered_at    TEXT NOT NULL,
                last_validated   TEXT,
                status           TEXT DEFAULT 'active',
                surfaced_count   INTEGER DEFAULT 0
            );

            CREATE TABLE IF NOT EXISTS reflections (
                id                  INTEGER PRIMARY KEY AUTOINCREMENT,
                content             TEXT NOT NULL,
                evidence_notebooks  TEXT DEFAULT '[]',
                evidence_concepts   TEXT DEFAULT '[]',
                importance          INTEGER DEFAULT 3,
                created_at          TEXT NOT NULL,
                surfaced            INTEGER DEFAULT 0
            );

            CREATE TABLE IF NOT EXISTS provenance (
                brain_artifact_type TEXT NOT NULL,
                brain_artifact_id   TEXT NOT NULL,
                source_type         TEXT NOT NULL,
                source_id           TEXT NOT NULL,
                notebook_id         TEXT
            );

            -- Entity-keyed cross-notebook insights — formerly in
            -- curator_insights.json, migrated 2026-05-12 (Curator Phase 1).
            -- Distinct from `reflections`: insights are short, entity-anchored,
            -- and generated by discover_cross_notebook_patterns; reflections
            -- are LLM-generated narrative observations.
            CREATE TABLE IF NOT EXISTS insights (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                insight_type    TEXT NOT NULL,
                entity          TEXT,
                notebooks       TEXT DEFAULT '[]',
                summary         TEXT NOT NULL,
                confidence      REAL DEFAULT 0.5,
                created_at      TEXT NOT NULL,
                surfaced_count  INTEGER DEFAULT 0,
                last_surfaced   TEXT,
                dismissed       INTEGER DEFAULT 0,
                thumbs_up       INTEGER DEFAULT 0
            );

            -- Event bus persistence — every @-prefix agent emits an event
            -- after its action completes. Brain's consumer loop reads from
            -- the in-memory queue; this table is the durable replay log
            -- in case the brain crashes mid-consume. Added 2026-05-12
            -- (Curator Phase 1). 30-day rolling window — rotation TODO.
            CREATE TABLE IF NOT EXISTS events (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                ts              TEXT NOT NULL,
                notebook_id     TEXT,
                actor           TEXT NOT NULL,
                action          TEXT NOT NULL,
                intent          TEXT,
                payload         TEXT DEFAULT '{}',
                outcome         TEXT
            );

            -- Engagement telemetry — derived from event bus events plus
            -- explicit UI signals (Phase 2b). Powers smart morning brief
            -- (Phase 5) + calibrated uncertainty (Phase 4). Added Phase 2a.
            -- Local-only; gated by settings.engagement_tracking_enabled.
            CREATE TABLE IF NOT EXISTS engagement_events (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                ts              TEXT NOT NULL,
                notebook_id     TEXT,
                kind            TEXT NOT NULL,
                subject_type    TEXT,
                subject_id      TEXT,
                signal          TEXT NOT NULL,
                payload         TEXT DEFAULT '{}'
            );

            -- Plan-then-act ledger (Curator Phase 2a). Every user-visible
            -- multi-step curator action creates a plan row and one
            -- plan_steps row per step. Status transitions: proposed →
            -- running → completed/cancelled/failed. UI in Phase 2b will
            -- subscribe to plan_* events on the bus for live rendering.
            CREATE TABLE IF NOT EXISTS plans (
                plan_id          TEXT PRIMARY KEY,
                notebook_id      TEXT,
                intent           TEXT NOT NULL,
                summary          TEXT,
                status           TEXT NOT NULL,
                created_at       TEXT NOT NULL,
                started_at       TEXT,
                finished_at      TEXT,
                user_visible     INTEGER DEFAULT 1
            );

            CREATE TABLE IF NOT EXISTS plan_steps (
                step_id          INTEGER PRIMARY KEY AUTOINCREMENT,
                plan_id          TEXT NOT NULL,
                seq              INTEGER NOT NULL,
                name             TEXT NOT NULL,
                description      TEXT,
                status           TEXT NOT NULL,
                started_at       TEXT,
                finished_at      TEXT,
                output_summary   TEXT,
                FOREIGN KEY (plan_id) REFERENCES plans(plan_id)
            );

            -- Nag budget log (Curator Phase 3c — 2026-05-13). Records
            -- every proactive surface the curator fires plus the user's
            -- response (thumbs up/down/dismissed). Used by can_fire_nag
            -- to enforce daily cap + per-(kind, notebook) cool-off after
            -- repeated thumbs_down.
            CREATE TABLE IF NOT EXISTS nag_log (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                kind            TEXT NOT NULL,
                notebook_id     TEXT,
                subject_id      TEXT,
                fired_at        TEXT NOT NULL,
                user_response   TEXT
            );

            -- Pending overwatch asides — text generated by curator's
            -- maybe_fire_dissent_overwatch (and future kinds) that the
            -- next chat reply should surface. Each row is consumed once.
            -- Curator Phase 3c.
            CREATE TABLE IF NOT EXISTS pending_asides (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                notebook_id     TEXT NOT NULL,
                kind            TEXT NOT NULL,
                aside_text      TEXT NOT NULL,
                nag_id          INTEGER,
                created_at      TEXT NOT NULL,
                consumed_at     TEXT
            );

            -- Anticipatory drafts (Curator Phase 6a — 2026-05-13).
            -- The curator pre-drafts Studio outputs overnight for mature
            -- notebooks. Each draft is consumed once (user views it) or
            -- discarded (sets cool-off so we don't redraft).
            CREATE TABLE IF NOT EXISTS draft_outputs (
                id                 INTEGER PRIMARY KEY AUTOINCREMENT,
                notebook_id        TEXT NOT NULL,
                kind               TEXT NOT NULL,
                content_markdown   TEXT NOT NULL,
                source_signal      TEXT,
                created_at         TEXT NOT NULL,
                consumed_at        TEXT,
                discarded_at       TEXT
            );

            -- Manual brief topic suppression (Curator Phase 5 — 2026-05-13).
            -- Substring-match keyword list — when a story title contains
            -- any active key (case-insensitive), it's filtered out of
            -- the morning brief. notebook_id NULL = applies globally
            -- (rare; @curator suppress today defaults to notebook-scoped).
            CREATE TABLE IF NOT EXISTS topic_suppressions (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                notebook_id     TEXT,
                topic_key       TEXT NOT NULL,
                suppressed_at   TEXT NOT NULL,
                reason          TEXT,
                UNIQUE(notebook_id, topic_key)
            );

            -- Per-source stance scoring against the notebook thesis
            -- (Curator Phase 3b — 2026-05-13). Each source gets one row
            -- per notebook (UNIQUE constraint). When the thesis changes,
            -- existing rows become stale — detected via scored_thesis_hash
            -- mismatch and re-scored in batches.
            CREATE TABLE IF NOT EXISTS source_stances (
                id                  INTEGER PRIMARY KEY AUTOINCREMENT,
                source_id           TEXT NOT NULL,
                notebook_id         TEXT NOT NULL,
                stance              TEXT NOT NULL,
                confidence          REAL DEFAULT 0.5,
                rationale           TEXT DEFAULT '',
                scored_thesis_hash  TEXT NOT NULL,
                scored_at           TEXT NOT NULL,
                UNIQUE(source_id, notebook_id)
            );

            -- Mental model per notebook (Curator Phase 3a — 2026-05-13).
            -- Curator's evolving understanding of WHAT the user is doing
            -- in each notebook. User can view + edit + pin specific
            -- fields; pinned fields never get overwritten by inference.
            -- Stage values: exploration | gathering | synthesis | drafting | done
            CREATE TABLE IF NOT EXISTS mental_models (
                notebook_id        TEXT PRIMARY KEY,
                thesis             TEXT DEFAULT '',
                goals              TEXT DEFAULT '[]',
                audience           TEXT DEFAULT '',
                stage              TEXT DEFAULT '',
                blocked_on         TEXT DEFAULT '',
                recent_focus       TEXT DEFAULT '',
                pinned_fields      TEXT DEFAULT '[]',
                confidence         REAL DEFAULT 0.0,
                last_inferred_at   TEXT,
                last_user_edit_at  TEXT
            );

            CREATE INDEX IF NOT EXISTS idx_connections_status
                ON connections (status, strength DESC);
            CREATE INDEX IF NOT EXISTS idx_reflections_surfaced
                ON reflections (surfaced, created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_connections_pair
                ON connections (notebook_a, notebook_b, status);
            CREATE INDEX IF NOT EXISTS idx_insights_active
                ON insights (dismissed, created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_insights_entity
                ON insights (entity, dismissed);
            CREATE INDEX IF NOT EXISTS idx_events_recent
                ON events (ts DESC);
            CREATE INDEX IF NOT EXISTS idx_events_actor
                ON events (actor, ts DESC);
            CREATE INDEX IF NOT EXISTS idx_engagement_recent
                ON engagement_events (ts DESC);
            CREATE INDEX IF NOT EXISTS idx_engagement_kind
                ON engagement_events (kind, signal, ts DESC);
            CREATE INDEX IF NOT EXISTS idx_engagement_notebook
                ON engagement_events (notebook_id, ts DESC);
            CREATE INDEX IF NOT EXISTS idx_plans_recent
                ON plans (created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_plans_notebook
                ON plans (notebook_id, status, created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_plan_steps_plan
                ON plan_steps (plan_id, seq);
            CREATE INDEX IF NOT EXISTS idx_mental_models_inferred
                ON mental_models (last_inferred_at DESC);
            CREATE INDEX IF NOT EXISTS idx_stances_notebook
                ON source_stances (notebook_id, stance);
            CREATE INDEX IF NOT EXISTS idx_stances_dissent
                ON source_stances (notebook_id, stance, confidence DESC);
            CREATE INDEX IF NOT EXISTS idx_nag_log_recent
                ON nag_log (fired_at DESC);
            CREATE INDEX IF NOT EXISTS idx_nag_log_kind_nb
                ON nag_log (kind, notebook_id, fired_at DESC);
            CREATE INDEX IF NOT EXISTS idx_pending_asides_active
                ON pending_asides (notebook_id, consumed_at, created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_topic_suppressions_active
                ON topic_suppressions (notebook_id, topic_key);
            CREATE INDEX IF NOT EXISTS idx_drafts_active
                ON draft_outputs (notebook_id, consumed_at, discarded_at, created_at DESC);

            -- Per-source rolling reputation (Phase 7.6 prep — 2026-05-23).
            -- Capture-only at first: every source_added / source_approved /
            -- source_rejected event updates this table. Surfacing rule
            -- ("source X dropped from 80% to 20%") lands later once the
            -- table has enough data to be meaningful. One row per
            -- (notebook_id, source_id).
            CREATE TABLE IF NOT EXISTS source_reputation (
                id                INTEGER PRIMARY KEY AUTOINCREMENT,
                notebook_id       TEXT NOT NULL,
                source_id         TEXT NOT NULL,
                source_label      TEXT DEFAULT '',
                total_events      INTEGER DEFAULT 0,
                approved_count    INTEGER DEFAULT 0,
                rejected_count    INTEGER DEFAULT 0,
                added_count       INTEGER DEFAULT 0,
                rolling_30d_events INTEGER DEFAULT 0,
                rolling_30d_approved INTEGER DEFAULT 0,
                rolling_30d_rejected INTEGER DEFAULT 0,
                lifetime_acceptance_rate REAL DEFAULT 0.0,
                rolling_acceptance_rate REAL DEFAULT 0.0,
                first_seen_at     TEXT,
                last_event_at     TEXT,
                UNIQUE(notebook_id, source_id)
            );
            CREATE INDEX IF NOT EXISTS idx_source_reputation_nb
                ON source_reputation (notebook_id, rolling_acceptance_rate);
        """)
        self._conn.commit()
        self._migrate_legacy_insights()

    def _migrate_legacy_insights(self) -> None:
        """One-shot: pull curator_insights.json into the insights table.

        Idempotent — if the JSON file is gone (already migrated and
        renamed to .pre-v3-backup) this is a no-op. Run once at init
        time, after table creation.
        """
        legacy_path = Path(settings.data_dir) / "curator_insights.json"
        if not legacy_path.exists():
            return
        try:
            # Don't double-migrate if insights table already has rows.
            existing = self._conn.execute(
                "SELECT COUNT(*) FROM insights"
            ).fetchone()[0]
            if existing > 0:
                logger.info(
                    f"[CuratorBrain] insights table already populated ({existing} rows); "
                    f"backing up legacy file without re-migrating"
                )
                self._backup_legacy_insights(legacy_path)
                return

            data = json.loads(legacy_path.read_text())
            if not isinstance(data, list):
                logger.warning(f"[CuratorBrain] legacy insights file malformed (not a list); skipping")
                return

            count = self.add_insights(data)
            logger.info(f"[CuratorBrain] migrated {count} legacy insights from curator_insights.json")
            self._backup_legacy_insights(legacy_path)
        except Exception as e:
            logger.warning(f"[CuratorBrain] legacy insight migration failed (non-fatal): {e}")

    @staticmethod
    def _backup_legacy_insights(legacy_path: Path) -> None:
        """Rename curator_insights.json → curator_insights.json.pre-v3-backup."""
        backup_path = legacy_path.with_suffix(".json.pre-v3-backup")
        try:
            legacy_path.rename(backup_path)
            logger.info(f"[CuratorBrain] backed up legacy insights → {backup_path.name}")
        except Exception as e:
            logger.warning(f"[CuratorBrain] could not back up legacy insights: {e}")
